language: ruby
sudo: false

addons:
  apt:
    packages:
    - lftp
    - texlive-latex-recommended

cache:
  bundler: true
  directories:
  - tmp/.htmlproofer # cache external link checks

dist: trusty

rvm:
  - 2.4

bundler_args: --jobs 3 --retry 3 --path=${BUNDLE_PATH:-vendor/bundle}

env:
  global:
   # AM_TOKEN=     (to push)
   - secure: "LCM5+UqugSNJPaIT5cyBYVf2qM9qpgJJqJtbYlZJr5ymc27J6fGvW1ltNCCjE43bb+o84H95iLbKpFvotTNJQHoLs6QgdSSmZBke7D22qilnS9p7NI8Lcj+wmBry9lt/L5PjrGr6ZC6Zp9/YPWLMGvKH95GcKe6x031ZaKQXwDJIopMuouGPDTQgzwnrYPciVgOGlQUUmf7a7QaM3deD8yemYDmlnrxcXGwjb4yVtEXrNrt/Y0btMqLuyuMAxD2RMilMo3KxonM4cjRsdGf8ydHlFk+W0LnecrcurYOpqjUc4o7L4914h9M6WZohmFzY72rf+TULlTv7rJQluKvxTonoMJMOBBtGjYIsyy4s4ew+g4+kOYLKakkRzQvx7hYWgKjrwjKORXMMHTEC4I7By6UT2Y8JcbSfCMgc3s4/q1X2Bp8ziX3le4RxlfTSAVseC+4oMVJbZjEgiy4KcfB/PXNDV+IgyqZYxIWjmcqEVR0KK2gIoRwOSnvr+0EcMUdLh1re0m5Du+K2mBUqbPMNZisMhVtigRvEGvYOoUPp4Y5/d8m6YGHapvbsEj70yMGE6c1OY67qJ8u0xMkDa0pNCV7dOIBiFGKsaP7f5w8tUOtBDIfppUE8+tPIF9FNfJUtupNRCmejzTQnTyvEBC4mYAruVieNFCwVpiW5gbmR28k="
   # GH_TOKEN=     (to push)
   - secure: "PYe6iUG6bVR0sENqB50GnP44BNeWSTLKdqmsf72dYOOVxsttdKgDEQldczKMaOKw2FUCnK3rU1F2Gcy2eZJSYtfT5LqueryOex329QozxMLR1qmRZF03aoxHt6yuauAoA6DX0eLE73dpUQj1k+CM3+voEBxPLZ92Aw/K/eoEb0C9K9oyJ1lw9AMoHeNrCY7jmhstBDlmLgR9w8e43TNHqJ2wHLmuHk85mkT6OIbt2HTx4zTj4233THQbH7ie/Iab89U1fLRFH4JOH465IJYvr9i+txD4ANDFhJ6XFqOMvYdw3n9Yxq0K6fulgI+WddgnnsmewNxDMJ0QwJoPJu4NZai8p/uRel2LK2Zb5jfCCHpA2yEYajqds6j72DcCHsr1bqI5U4s17qC6jUAbXM3XX5wNEhJsuV5m55MXcLGWGJne6KSZWNWRnKXoYQ6WaUmj6Lm3RYQWCxDbaX6BCLL3+mhTvrt0Ic3pPUzt4kecp8ImV9mEdLJ8KKv7Aaodk9c4kwVdWzgunh7VCilZfvTV3tMh0gmgpczcAYDMa9EeXOLeUu4O/MU8I02WFaURoIYMvd7s8HB9LadSRKlE3UyrPeYm2b/dCBThA6jLbocjUbgYp01oks8WrikHIMXeiGXzXAhFq8hn8vGKvGJFvBm+LMUAWC1FTW/Q3+F5+0cJmo0="

before_install:
  - export PATH="$TRAVIS_BUILD_DIR/_lab_site/_bin:$PATH"
  - gem update bundler

install: bundle install
script:
  - cp -R ./_lab_site/publications ./
  - bundle exec jekyll build
  - bundle exec ruby scripts/htmlproof.rb
after_success: bash scripts/deploy.sh
notifications:
  email:
    recipients:
     - travis-builds@ameyer.me
