name: Jekyll build

on:
  push
    
jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
    - run: bundle install
    - run: cd publications; wget https://asmlab.org/publications/pubs_bib.html
    - run: cd publications; wget https://asmlab.org/publications/pub_build.html
    - run: bundle exec jekyll build
    - run: bundle exec htmlproofer --check-html --http-status-ignore "999,400" --assume-extension ./_site
